name: Deploy with GitHub Actions on Deno Deploy

env:
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v3
      - name: Deno deploy Solid Start
        uses: fbritoferreira/deno-deploy-solid-start@v1
        with:
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
          project: "./"
          build: true
          deploy: true
          install: true
